---
title: "Escolas Integrais em Pernambuco"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(data.table, dplyr, leaflet, leaflet.extras, leaflet.minicharts, plotly, rgdal, tidyr) # carregar os pacotes

escolas_integrais <- fread('https://raw.githubusercontent.com/hugoavmedeiros/cp_com_r/master/bases_tratadas/escolas_tempo_integral_v2.csv') # carregar a base de dados

escolas_integrais$nome_escola <- as.factor(escolas_integrais$nome_escola) # conversão de dados

escolas_integrais_agg <- escolas_integrais %>% group_by(nome_escola, ano_implantacao, .drop=FALSE) %>% summarise(n = n()) %>% na.omit() 
# %>% complete(ano_implantacao, nome_escola, fill = list(n = 0)) %>% filter(nome_escola != '') %>% distinct()

escolas_integrais_agg <- merge(escolas_integrais_agg, escolas_integrais, by = 'nome_escola') %>% select(!ano_implantacao.y) %>% distinct()

escolas_integrais_ano <- escolas_integrais %>% group_by(ano_implantacao) %>% summarise(n = n()) %>% mutate(n_ant = lag(n, 10L))

```

## Evolução da Rede Integral

### Série Histórica

```{r sh, echo=FALSE, warning=FALSE, message=FALSE}

plot_ly(escolas_integrais_ano, x = ~ano_implantacao) %>% add_trace(y = ~n_ant, name = 'década anterior', mode = 'lines+markers') %>% add_trace(y = ~n, name = 'ano', mode = 'lines+markers')

```

### Mapa Interativo

```{r mi, echo=FALSE, warning=FALSE, message=FALSE}

leaflet(escolas_integrais_agg) %>% addTiles() %>%
  addMinicharts(
    escolas_integrais_agg$lon, escolas_integrais_agg$lat,
    chartdata = escolas_integrais_agg$n,
    time = escolas_integrais_agg$ano_implantacao.x,
    showLabels = F,
    width = 15, height = 15
  ) %>%
  addFullscreenControl()

```

