---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
# carregar as bibliotecas
pacman::p_load(cluster, ggplot2)

# pré-processamento
iris_cluster <- iris[ , -5]
str(iris_cluster)

# setar semente aleatória
set.seed(1)

# Agrupamento com kmeans
cls <- kmeans(x = iris_cluster, centers = 3) # aprendizagem ns
iris_cluster$cluster <- as.factor(cls$cluster) # passamos os clusters para a base original
head(iris_cluster)
```

# Agrupamento dos dados 'Iris'
## K-means

Abaixo, você encontra o agrupamento da base de dados Iris, usando a técnica de k-means.

```{r iris}
ggplot() +
  geom_point(data = iris_cluster, 
             mapping = aes(x = Sepal.Length, 
                           y = Petal.Length, 
                           colour = cluster)) +
  geom_point(mapping = aes_string(x = cls$centers[ , "Sepal.Length"], 
                                  y = cls$centers[ , "Petal.Length"]),
             color = "red", size = 4) +
  geom_text(mapping = aes_string(x = cls$centers[ , "Sepal.Length"], 
                                 y = cls$centers[ , "Petal.Length"],
                                 label = 1:3),
            color = "white", size = 2) +
  theme_light()
```

Observe que existe um cluster (nro 1) bastante separados dos outros. Alguns pontos desses dois clusters (nro 2 e nro 3) são semelhantes, dificultando a aprendizagem da máquina