---
title: "Municípios de Pernambuco"
output:
   flexdashboard::flex_dashboard:
    orientation: rows
    # vertical_layout: scroll
    theme: lumen
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(corrplot, dplyr, DT, flexdashboard, funModeling, lubridate, shiny, zoo) # carregar pacotes

source('municipios_processamento.R')

# mun_pe <- read.csv2('../../bases_tratadas/clusters_municipios_pe.csv')

```

Análise de Indicadores {data-icon="fa-chart-line" data-orientation=rows}
===================================== 

Controles {.sidebar}
-------------------------------------

```{r controle1, echo=FALSE, warning=FALSE, message=FALSE}

radioButtons(inputId = 'radio1', 'Selecione a RD', c('PERNAMBUCO', unique(levels(mun_pe$rd))), inline = F)
```

Row
-------------------------------------

### Distribuição dos indicadores

```{r hist, echo=FALSE, warning=FALSE, message=FALSE}
renderPlot({
  
  if(input$radio1 == "PERNAMBUCO") {
  
    plot_num(mun_pe [ , c(4:6, 10:14) ] )
    
    }
  
  else {
    
    m <- mun_pe %>% filter(rd == input$radio1) ## dinâmica
    
    plot_num(m[ , c(4:6, 10:14) ] )
    
  }
  
})
```

Row
-------------------------------------

### Relacionamento entre os indicadores

```{r cor, echo=FALSE, warning=FALSE, message=FALSE}
renderPlot({
  
  if(input$radio1 == "PERNAMBUCO") {
  
    corrplot(cor(mun_pe[, c(4:6, 10:14)]))
    
    }
  
  else {
    
    m <- mun_pe %>% filter(rd == input$radio1) ## dinâmica
    
    corrplot(cor(m[, c(4:6, 10:14)]))
    
  }
  
})
```

Agrupamento {data-icon="fa-object-group" data-orientation=rows}
===================================== 

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r controle2, echo=FALSE, warning=FALSE, message=FALSE}

shiny::radioButtons(inputId = 'radio2', 'Selecione a RD', c('PERNAMBUCO', unique(levels(mun_pe$rd))), inline = F)

shiny::radioButtons(inputId = 'radio3', 'Escolha o Total de Grupos', 1:12, inline = T)
```

Row
-------------------------------------

### Agrupamento 

```{r cluster, echo=FALSE, warning=FALSE, message=FALSE}
renderPlot({
  
  if(input$radio2 == "PERNAMBUCO") {
  
    cls <- kmeans(x = mun_pe [, c(4:6, 10:14)], centers = 12)
    
    mun_pe$cluster <- as.factor(cls$cluster)
    
  ggplot() +
  geom_point(data = mun_pe, 
             mapping = aes(x = vab, 
                           y = salario_medio, 
                           colour = cluster)) +
  theme_light()
    
    }
  
  else {
    
    m <- mun_pe %>% filter(rd == input$radio2) ## dinâmica
    
    cls <- kmeans(x = m [, c(4:6, 10:14)], centers = input$radio3) ## dinâmica
    
    m$cluster <- as.factor(cls$cluster)
    
  ggplot() +
  geom_point(data = m, 
             mapping = aes(x = vab, 
                           y = salario_medio, 
                           colour = cluster)) +
  theme_light()
    
  }
  
})
```

Metadados {data-icon="fa-info" data-orientation=rows}
=====================================

Veja abaixo a tabela com as informações detalhadas dos indicadores <br> `r knitr::kable(mun_pe_meta) # inline` 